export const ID = 'SIGNUP/ID' as const;
export const PASSWORD = 'SIGNUP/PASSWORD' as const;
export const NICKNAMD = 'SIGNUP/NICKNAME' as const;
export const WHITECHECK = 'SIGNUP/WHITECHECK' as const;

export const SIGNUP = 'SIGNUP/SIGNUP' as const;
export const SIGNUP_SUCCESS = 'SIGNUP/SIGNUP_SUCCESS' as const;
export const SIGNUP_FAILURE = 'SIGNUP/SIGNUP_FAILURE' as const;

export const ID_DUPLICATECHECK = 'SIGNUP/ID_DUPLICATECHECK' as const;
export const ID_DUPLICATECHECK_SUCCESS = 'SIGNUP/ID_DUPLIACTECHECK_SUCCESS' as const;
export const ID_DUPLICATECHECK_FAILURE = 'SIGNUP/ID_DUPLICATECHECK_FAILURE' as const;

export const NICKNAME_DUPLICATECHECK = 'SIGNUP/NICKNAME_DUPLICATECHECK' as const;
export const NICKNAME_DUPLICATECHECK_SUCCESS = 'SIGNUP/NICKNAME_DUPLICATECHECK_SUCCESS' as const;
export const NICKNAME_DUPLICATECHECK_FAILURE = 'SIGNUP/NICKNAME_DUPLICATECHECK_FAILURE' as const;
